package tangzeqi.com.ui.broser;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import tangzeqi.com.tools.broser.Broser;
import tangzeqi.com.tools.broser.server.MyJCEF;
import tangzeqi.com.ui.MyPanel;

import javax.swing.*;
import java.awt.*;

public class BrowserPanel extends JPanel implements MyPanel {
    private final String project;

    private JPanel browserPanel;
    private JPanel browserBar;
    private JTextField urlField;
    private JButton goButton;
    private JPanel browserContentPanel;

    // 浏览器
    private Broser browser;

    public BrowserPanel(String project) {
        this.project = project;
        $$$setupUI$$$();
        initializeBrowser();
        setupEventHandlers();
    }

    public BrowserPanel() {
        this.project = null;
    }

    // 添加浏览器初始化方法
    private void initializeBrowser() {
        browser = new MyJCEF(project);
        // 添加浏览器主视图
        // 直接添加浏览器组件，而不是遍历获取组件
        for (Component component : browser.getComponents()) {
            if (component != null) {
                browserContentPanel.add(component);
            }
        }
    }

    private void setupEventHandlers() {
        // URL加载事件处理
        urlField.addActionListener(e -> {
            String url = urlField.getText();
            if (!url.trim().isEmpty()) {
                loadURL(url);
            }
        });

        goButton.addActionListener(e -> {
            String url = urlField.getText();
            if (!url.trim().isEmpty()) {
                loadURL(url);
            }
        });

        // 加载初始URL
        loadURL(urlField.getText());
    }

    // 修改loadURL方法
    private void loadURL(String url) {
        if (browser != null) {
            if (!url.startsWith("http://") && !url.startsWith("https://")) {
                url = "http://" + url;
            }
            browser.loadURL(url);
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("BrowserPanel");
            frame.setContentPane(new BrowserPanel().browserPanel);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.pack();
            frame.setVisible(true);
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        browserPanel = new JPanel();
        browserPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        browserPanel.setMinimumSize(new Dimension(-1, -1));
        browserPanel.setPreferredSize(new Dimension(-1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        browserPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        urlField = new JTextField();
        urlField.setPreferredSize(new Dimension(600, 25));
        urlField.setText("https://www.cnblogs.com/tangzeqi");
        panel1.add(urlField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        goButton = new JButton();
        goButton.setPreferredSize(new Dimension(60, 25));
        goButton.setText("访问");
        panel1.add(goButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        browserPanel.add(browserContentPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return browserPanel;
    }

    private void createUIComponents() {
        browserContentPanel = new JPanel(new BorderLayout());
    }

    @Override
    public JComponent getComponent(String project) {
        return new BrowserPanel(project).$$$getRootComponent$$$();
    }
}
